# The URL the site will be built for
base_url = "https://fundon.viz.rs"

title = "🦀"

description = "Learn, create, share, enjoy, and feel."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true

minify_html = true

theme = "viz"

taxonomies = [
  { name = "tags", paginate_by = 5, rss = true },
]

extra_syntaxes_and_themes = ["highlight_themes"]

[markdown]
highlight_code = true
# highlight_theme = "dracula"

highlight_theme = "css"
highlight_themes_css = [
  { theme = "catppuccin-latte" },
  { theme = "catppuccin-macchiato" },
]

[extra]
author = ""
github = ""
twitter = ""
email = ""
banner = "images/tide.jpeg"
