base_url = "https://fundon.viz.rs"

title = "🦀"

description = "Learn, create, share, enjoy, and feel."

compile_sass = true

build_search_index = true

generate_feed = true

minify_html = true

theme = "viz"

taxonomies = [
  { name = "tags", paginate_by = 5, rss = true },
]

extra_syntaxes_and_themes = ["highlight_themes"]

[markdown]
highlight_code = true
# highlight_theme = "dracula"

highlight_theme = "css"
highlight_themes_css = [
  { theme = "catppuccin-latte" },
  { theme = "catppuccin-macchiato" },
]

[extra]
author = "Fangdun Tsai"
github = "fundon"
twitter = "_fundon"
email = ""
banner = "images/tide.jpeg"
